### ISSUE TITLE
Error in Debian

### ISSUE THREAD

**Issue by JJ** [frithnanth/perl6-Archive-Libarchive-Raw#6]
When testing it inside a Debian container, test fails with:

```
not ok 8 - uid
# Failed test 'uid'
# at t/05-archive-read-disk.t line 21
not ok 9 - gid
# Failed test 'gid'
# at t/05-archive-read-disk.t line 22
```

**Comment by JJ** [comment]
Those functions apparently return 0 in that container (based in my rakudo-nostar container)

**Comment by JJ** [comment]
0 is UID for root. That's the error if it's run from root, apparently. It might be an error, anyway...

**Comment by frithnanth** [comment]
Thank you!
